name: dt_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.2
  flutter_bluetooth_serial: ^0.4.0
  mobile_scanner: ^3.2.0
  permission_handler: ^11.0.1

  




  # UI
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_analytics: ^11.4.5

  # Payment Gateway
  razorpay_flutter: ^1.3.5
  

  # Barcode Scanner

  # Local Storage
  shared_preferences: ^2.0.15
  hive: ^2.0.6
  hive_flutter: ^1.1.0

  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.2.1

  # Navigation and Routing
  go_router: ^14.8.1

  # Internationalization
  easy_localization: ^3.0.0
  flutter_localizations:
    sdk: flutter

  # Form Validation (updated)
  flutter_form_builder: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.3.0

flutter:
  uses-material-design: true
